AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Continuous Deployment settings for holidays in Japan

Resources:
  # Permission Boundary for CI/CD Roles
  DeploymentPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Permission Boundary for holidays-jp CI/CD Roles
      ManagedPolicyName: !Sub "holidays-jp-permission-boundary-${AWS::Region}"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: ServiceBoundaries
            Effect: Allow
            Action:
              - "logs:*"
              - "ssm:*"
            Resource: "*"

  # CloudFormation Service Role for deploying SAM templates
  DeploymentRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "holidays-jp-cfn-service-role-${AWS::Region}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - cloudformation.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: deploy-sam-templates
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: CreateOrChangeOnlyWithBoundary
                Effect: Allow
                Action:
                  - "iam:CreateUser"
                  - "iam:DeleteUserPolicy"
                  - "iam:AttachUserPolicy"
                  - "iam:DetachUserPolicy"
                  - "iam:PutUserPermissionsBoundary"
                  - "iam:PutUserPolicy"
                Resource: "*"
                Condition:
                  StringEquals:
                    "iam:PermissionsBoundary": !Ref DeploymentPolicy
              - Sid: NoBoundaryPolicyEdit
                Effect: Deny
                Action:
                  - "iam:CreatePolicyVersion"
                  - "iam:DeletePolicy"
                  - "iam:DeletePolicyVersion"
                  - "iam:SetDefaultPolicyVersion"
                Resource:
                  - !Ref DeploymentPolicy
              - Sid: NoBoundaryUserDelete
                Effect: Deny
                Action:
                  - "iam:DeleteUserPermissionsBoundary"
                Resource: "*"
              - Sid: OtherIAMTasks
                Effect: Allow
                Action:
                  - "iam:GetUser"
                  - "iam:ListUsers"
                  - "iam:DeleteUser"
                  - "iam:UpdateUser"
                  - "iam:CreateAccessKey"
                  - "iam:CreateLoginProfile"
                  - "iam:GetAccountPasswordPolicy"
                  - "iam:GetLoginProfile"
                  - "iam:ListGroups"
                  - "iam:ListGroupsForUser"
                  - "iam:CreateGroup"
                  - "iam:GetGroup"
                  - "iam:DeleteGroup"
                  - "iam:UpdateGroup"
                  - "iam:CreatePolicy"
                  - "iam:DeletePolicy"
                  - "iam:DeletePolicyVersion"
                  - "iam:GetPolicy"
                  - "iam:GetPolicyVersion"
                  - "iam:GetUserPolicy"
                  - "iam:GetRolePolicy"
                  - "iam:ListPolicies"
                  - "iam:ListPolicyVersions"
                  - "iam:ListEntitiesForPolicy"
                  - "iam:ListUserPolicies"
                  - "iam:ListAttachedUserPolicies"
                  - "iam:ListRolePolicies"
                  - "iam:ListAttachedRolePolicies"
                  - "iam:SetDefaultPolicyVersion"
                  - "iam:SimulatePrincipalPolicy"
                  - "iam:SimulateCustomPolicy"
                Resource: "*"
              - Sid: CloudFormationStackOperation
                Effect: Allow
                Action:
                  - "cloudformation:CancelUpdateStack"
                  - "cloudformation:ContinueUpdateRollback"
                  - "cloudformation:CreateChangeSet"
                  - "cloudformation:CreateStack"
                  - "cloudformation:DeleteChangeSet"
                  - "cloudformation:DeleteStack"
                  - "cloudformation:DescribeChangeSet"
                  - "cloudformation:DescribeStackEvents"
                  - "cloudformation:DescribeStackResource"
                  - "cloudformation:DescribeStackResourceDrifts"
                  - "cloudformation:DescribeStackResources"
                  - "cloudformation:DescribeStacks"
                  - "cloudformation:DetectStackDrift"
                  - "cloudformation:DetectStackResourceDrift"
                  - "cloudformation:ExecuteChangeSet"
                  - "cloudformation:GetStackPolicy"
                  - "cloudformation:GetTemplate"
                  - "cloudformation:GetTemplateSummary"
                  - "cloudformation:ListChangeSets"
                  - "cloudformation:ListStackResources"
                  - "cloudformation:RecordHandlerProgress"
                  - "cloudformation:SetStackPolicy"
                  - "cloudformation:SignalResource"
                  - "cloudformation:UntagResource"
                  - "cloudformation:UpdateStack"
                  - "cloudformation:UpdateTerminationProtection"
                Resource:
                  - !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/holidays-jp/*"
                  - !Sub "arn:aws:cloudformation:${AWS::Region}:aws:transform/Serverless-2016-10-31"
