AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Continuous Deployment settings for holidays in Japan

Resources:
  # Permission Boundary for CI/CD Roles
  DeploymentPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Permission Boundary for holidays-jp CI/CD Roles
      ManagedPolicyName: !Sub "holidays-jp-permission-boundary-${AWS::Region}"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: ServiceBoundaries
            Effect: Allow
            Action:
              - "logs:*"
              - "ssm:*"
            Resource: "*"

  # CloudFormation Service Role for deploying SAM templates
  DeploymentRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "holidays-jp-cfn-service-role-${AWS::Region}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - cloudformation.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: deploy-sam-templates
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: CreateOrChangeOnlyWithBoundary
                Effect: Allow
                Action:
                  - "iam:CreateRole"
                  - "iam:DeleteRolePolicy"
                  - "iam:DeleteRolePermissionsBoundary"
                  - "iam:DetachRolePolicy"
                Resource: "*"
                Condition:
                  StringEquals:
                    "iam:PermissionsBoundary": !Ref DeploymentPolicy
              - Sid: NoBoundaryPolicyEdit
                Effect: Deny
                Action:
                  - "iam:CreatePolicyVersion"
                  - "iam:DeletePolicy"
                  - "iam:DeletePolicyVersion"
                  - "iam:SetDefaultPolicyVersion"
                Resource:
                  - !Ref DeploymentPolicy
              - Sid: NoBoundaryUserDelete
                Effect: Deny
                Action:
                  - "iam:DeleteUserPermissionsBoundary"
                Resource: "*"
              - Sid: OtherIAMTasks
                Effect: Allow
                Resource: "*"
                Action:
                  # handle IAM Roles
                  - "iam:ListRolePolicies"
                  - "iam:ListRoleTags"
                  - "iam:ListRoles"
                  - "iam:GetRole"
                  - "iam:GetRolePolicy"
                  - "iam:ListAttachedRolePolicies"
                  - "iam:UpdateRole"
                  - "iam:UpdateRoleDescription"
                  - "iam:UpdateAssumeRolePolicy"
                  - "iam:PutRolePermissionsBoundary"
                  - "iam:PutRolePolicy"
                  - "iam:TagRole"
                  - "iam:UntagRole"
                  - "iam:DeleteRole"

                  # handle Service Linked Roles
                  - "iam:ListPoliciesGrantingServiceAccess"
                  - "iam:CreateServiceLinkedRole"
                  - "iam:DeleteServiceLinkedRole"
                  - "iam:GetServiceLinkedRoleDeletionStatus"

              - Sid: CloudFormationStackOperation
                Effect: Allow
                Action:
                  - "cloudformation:*"
                  - "lambda:*"
                  - "route53:*"
                  - "acm:*"
                  - "apigateway:*"
                  - "s3:*"
                Resource:
                  - "*"
