name: Update
on:
  schedule:
    - cron: "15 7 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17"

      - name: Generate token
        id: token
        uses: shogo82148/actions-github-app-token@v0
      - name: Check out code
        uses: actions/checkout@v2
        with:
          token: ${{ steps.token.outputs.token }}

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install Dependencies
        run: go mod download

      - name: Update syukujitsu.csv
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          DATE=$(date +%Y%m%d-%H%M%S)
          BRANCH=update-$DATE
          git switch -c "$BRANCH"
          go run ./internal/gen/gen.go
          git diff --exit-code --quiet && exit
          git add .
          git config --global user.email "shogo82148@gmail.com"
          git config --global user.name "Ichinose Shogo"
          git commit -m "update syukujitsu.csv $DATE"
          git push -u origin "$BRANCH"
          gh pr create --base main --head "$BRANCH" --title "update syukujitsu.csv $DATE" \
            --body "auto generated by [Update Workflow](${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID})"
